version: 2
jobs:
  build:
    docker:
      - image: greysonr/godot_butler:0.1.1

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "e9:82:1d:cc:68:5a:16:5e:ac:53:72:e5:17:03:b5:ca"

      - run:
          name: insert public key
          command: echo "$deploy_public_key" > ~/.ssh/lobby_server_deploy2_rsa.pem

      - run:
          name: add server to known_hosts
          command: echo "$SERVER_KNOWN_HOSTS_ENTRY" >> ~/.ssh/known_hosts

      - run:
          name: build_and_deploy
          command: |
            ls -al
            chmod +x ./tools/build-and-deploy.sh
            ./tools/build-and-deploy.sh
